# For development
version: "3"
services:
  web_flask:
    build:
      context: .
      args:
        project_directory: "/projects/"
    ports:
      - "5000:5000"
    volumes:
      - ".:/projects"
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
    command: "flask run --host 0.0.0.0 --port 5000"